name: Deploy PWA El Cauca

on:
  push:
    branches:
      - main  # Se activa cada vez que subes cambios a la rama principal

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: . # Sube todo el contenido de la carpeta raíz
          branch: gh-pages # Lo despliega en esta rama para la web
